# Generated by Django 5.0.6 on 2024-06-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='slot',
            new_name='time_in',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_out',
            field=models.CharField(choices=[('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00'), ('00:00', '00:00')], default='18:00', max_length=8),
        ),
    ]
