# Generated by Django 5.0.6 on 2024-06-30 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_event_excerpt_event_event_image_and_more'),
        ('booking', '0002_delete_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_size', models.IntegerField(default=2)),
                ('booking_slot', models.IntegerField(choices=[(1, '18:00 - 19:45'), (2, '20:00 - 21:45'), (3, '22:00 - 23:45'), (4, '00:00 - 01:45'), (5, '02:00 - 04:00')], default=1)),
                ('allergies', models.BooleanField(default=False)),
                ('special', models.CharField(max_length=250)),
                ('booking_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_guest', to=settings.AUTH_USER_MODEL)),
                ('booking_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_table', to='booking.table')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='about.event')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package', to='booking.package')),
            ],
            options={
                'ordering': ['booking_date', 'booking_slot'],
            },
        ),
    ]
