# Generated by Django 5.0.6 on 2024-06-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_slot_timeslot_time_in_timeslot_time_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_in',
            field=models.CharField(choices=[('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00'), ('00:00', '00:00'), ('01:00', '01:00'), ('02:00', '02:00')], default='18:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_out',
            field=models.CharField(choices=[('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00'), ('00:00', '00:00'), ('01:00', '01:00'), ('02:00', '02:00')], default='18:00', max_length=8),
        ),
        migrations.CreateModel(
            name='TableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Taken')], default=0)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='booking.table')),
                ('time_slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='booking.timeslot')),
            ],
        ),
    ]
