# Generated by Django 5.0.6 on 2024-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_package_table_alter_timeslot_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.CharField(default='£', max_length=5),
        ),
    ]
