# Generated by Django 5.0.6 on 2024-06-25 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tippleuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tippleuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tippleuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tippleuser',
            name='status',
        ),
        migrations.AddField(
            model_name='tippleuser',
            name='custom_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='custome_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
