# Generated by Django 5.0.6 on 2024-06-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tippleuser',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
